### PR TITLE
Write untagged nodes by default

### PR DESCRIPTION
**Pull request by patrickbr**
This PR removes the option `--write-way-node-geometries` and handles untagged nodes in exactly the same manner as tagged nodes.

### CODE REVIEW

**Review by lehmann-4178656ch — APPROVED** [review]

**Comment by lehmann-4178656ch** [comment]
Any idea why the non-stdout E2E builds keep failing @patrickbr ?

**Comment by patrickbr** [comment]
No idea, it seems like a memory issue, maybe caused by the increased input size to QLever (because of the non-tagged nodes). A quick mitigation would be to add options `--skip-untagged-nodes`, `--skip-untagged-ways` and `--skip-untagged-relations`.

**Comment by lehmann-4178656ch** [comment]
I'd prefer to switch the test dataset to something smaller first. Looking at https://osm2rdf.cs.uni-freiburg.de/ Malta has (with the old code) ~12.3M triples. Gibralta would have ~3.6M or Greenland ~3.2M. Are there some specific features in Malta we need for the E2E tests?

What I find very interesting is that writing to [stdout](https://github.com/ad-freiburg/osm2rdf/actions/runs/11818297662/job/32940426453?pr=101) worked. Granted it does not require memory for decompressing the data, but so should the [uncompressed](https://github.com/ad-freiburg/osm2rdf/actions/runs/11818297664/job/32977426397?pr=101) output test which fails.

**Comment by patrickbr** [comment]
I changed the E2E test dataset to Liechtenstein, let's see what happens.

**Review by lehmann-4178656ch — APPROVED** [review]

**Pull request merged**
