### PR TITLE
Basic geometries for Relations

### LINKED ISSUE #33: River has no geometry

### PR DESCRIPTION
**Pull request by lehmann-4178656ch**
This PR adds basic geometries for relations. These geometries only contain the direct Node and Way members of the relation.

This solves the problem of missing geometries as mentioned in #33 and thus fixes #33 for now.

### CODE REVIEW

**Comment by patrickbr** [comment]
@lehmann-4178656ch, this looks good and works on my machine, but have you tested this using the provided Dockerfile? AFAIK, Ubuntu 20.04 provides Boost 1.72. I tested it on `ob`, which is running Ubuntu 22.04 with Boost 1.74, and it complained that `geometry_collection` was not defined:

    /local/data/brosip/osm2rdf/src/../include/osm2rdf/geometry/Relation.h:33:33: error: no template named 'geometry_collection' in namespace 'boost::geometry::model' 

Debian 12 also hast Bosot 1.74. I am a bit hesitant to merge a pull request which won't compile on both the latest Ubuntu and Debian releases. What do you think?

**Comment by lehmann-4178656ch** [comment]
You're right, I should have tested that but I did only check against my machine which is a Fedora 37 shipping boost 1.78 at the time of writing. This PR would change the required version of boost to 1.77 or higher, maybe 1.78 or higher.

A quick check on [Debian 12](https://wiki.debian.org/DebianBookworm) which will freeze packages in march looks not promising right now. A search on [packages.debian.org](https://packages.debian.org/search?suite=bookworm&section=all&arch=amd64&searchon=names&keywords=libboost) still yields only boost 1.74, same for [Ubuntu 22.10](https://packages.ubuntu.com/search?suite=kinetic&section=all&arch=amd64&keywords=libboost&searchon=names). I've yet to find a way to query for Ubuntu 23.04 (Lunar Lobster).

From a usability point of view I'd agree with you and not merge this until a more recent versions of boost is readily available in the distributions. Trying to guard this feature would increase the complexity of the source files and could be required for a extended period of time.

I think we should involve @hannahbast as she opened #33 and ask for here input.

**Comment by patrickbr** [comment]
@lehmann-4178656ch and I just discussed the guard solution mentioned above. I think this is the best solution, as it enables us to update Boost in the Docker container running on ob, thus enabling the relation geometries in the dumps on osm2rdf.cs.uni-freiburg.de

The guards would look as follows:

    #if BOOST_VERSION >= 107700
      lorem_ipsum();
    #endif

@lehmann-4178656ch, could you look into this?

**Comment by lehmann-4178656ch** [comment]
I think I've marked all relevant places. Testing was not 100% as the podman/docker... setup on my machine throws some errors regarding the filesystem usage.

**Comment by patrickbr** [comment]
Thanks Axel! The testing problem is not present on my machine outside of a container environment.

**Pull request merged**
