### PR TITLE
Write triples for complete geo:sfContains and geo:sfIntersects

### PR DESCRIPTION
**Pull request by hannahbast**
Since https://github.com/ad-freiburg/qlever/commit/2fefc08d1793d18b9f6d81b902e80cf68c1a1a31 , QLever can join with very large predicates "lazily", that is, without fully materializing them in RAM first.

`osm2rdf` already had an option `--write-transitive-closure`, but that wrote transitive closures of `osm2rdf:contains_area` and `osm2rdf:contains_nonarea` separately. Now `--write-transitive-closure` writes the full `ogc:sfContains` predicate (and also still the old `osm2rdf:contains_area` and `osm2rdf:contains_nonarea` predicates, which are small in comparison though). For `ogc:sfIntersects` I did something similar, but I don't think the predicate is complete yet.

@patrickbr @lehmann-4178656ch I have the following questions, maybe you can help:

1. I am pretty sure that `geo:sfContains` is now complete the way I did it (I compared it with the previous synthesized `geo:contains`). For `geo:sfIntersects`, I don't think it's complete yet because there are `osm2rdf:intersects_area` and ``osm2rdf:intersects_nonarea` triples written out at so many places in the code, and I am not sure which of them should also be `geo:sfIntersects`.

2. I think we should have two options: `--write-geo-contains-and-intersects-triples` (which writes the triples for `geo:sfContains` and `geo:sfIntersects`) and `--write-osm2rdf-contains-and-intersects-triples` (which writes the triples for `osm2rdf:contains_area`, `osm2rdf:contains_nonarea`, `osm2rdf:intersects_area`, and `osm2rdf:intersects_nonarea` as before), and the default should be that the former is on by default and the latter is off. The names for the options are just suggestions.

### CODE REVIEW

**Comment by patrickbr** [comment]
I would prefer the following behavior:

1. Default behavior: write `geo:sfContains` and `geo:sfIntersects` with full transitive closure of `sfContains`.
2. Add option `--transitive-reduction` to restore the current behavior of dropping explicit `contains*`- and `intersects*`-relations which can be replaced by a `contains*/contains*` or `contains*/intersects*` path
3. Add option `--write-osm2rdf-contains-and-intersects-triples` for backwards compatibility.

Builds with `--transitive-reduction --write-osm2rdf-contains-and-intersects-triples` would emulate the current default behavior.

Builds with `--transitive-reduction` would be an option for https://osm2rdf.uni-freiburg.de where the transitive closure would be overkill for many users.

What do you think?

**Review by patrickbr — COMMENTED** [review]
I am not entirely sure that only replacing the predicates in the calls to `writeTransitiveClosure` is correct. `writeTransitiveClosure` writes for example `contains`-relations for all DAG successors of an area. So as I understand it, if `A contains B` and `B contains C`, then the current behavior was that the triple `B geo:contains_area C` is written, but not the triple `A geo:contains_area C`, as `A` is a successor of `B` in the DAG.

The call to `writeTransitiveClosure` then takes all successors `S` of `B` and also writes the triple  `S geo:contains_area C`, if requested.

This commit changes the predicate used in the call to `writeTransitiveClosure` to `sfContains`. But if I am not mistaken, this means that in the example above, only `A geo:sfContains C` is written, but not `B geo:sfContains C`. For the latter, the original predicate `geo:contains_area` is used, as `B` is not a successor of `B`.

**Comment by patrickbr** [comment]
I added two commits which implement the behavior described above.

In particular:

- Write `sfContains` and `sfIntersects` per default.
- Write transitive closure of contains relation per default
- Add option `--transitive-reduction`: only write transitive reduction of contains relation (and contains*/intersect)
- Add option `--write-osm2rdf-contains-and-intersects-triples`: also write "old style" `_area` and `_nonarea` geometric relations

**Comment by hannahbast** [comment]
@patrickbr Thanks a lot for these changes! I built a new TTL file and index for OSM Germany. The number of results for ["all streets in Freiburg"](https://qlever.cs.uni-freiburg.de/osm-germany/q46NYb) is the same as before, as it should be. The number of results for ["all streets in Stühlinger-Eschholz"](https://qlever.cs.uni-freiburg.de/osm-germany/1PDP0z) now contains 16 streets that were missing previously, including [Lederleplatz](https://www.openstreetmap.org/way/27456922). 

To test `ogc:sfIntersects`, I tried ["all streets intersecting Colombipark"](https://qlever.cs.uni-freiburg.de/osm-germany/TFYTc4), which gave obviously incomplete results yesterday and now looks good.

As discussed yesterday, I think we should allow all six combinations of writing triples for geometric relations. Here is a suggestion to do it with two options, but feel free to choose different names or options:

1. An option `--write-osm2rdf-contains-and-intersects-triples` with options `none` (the default), `reduced`, `full`.
3. An option `--write-ogc-contains-and-intersects-triples` with options `none`, `reduced`, `full` (the default).

**Comment by patrickbr** [comment]
I now added the options `--write-ogc-geo-triples` and `--write-osm2rdf-geo-triples` which behave in the way described above.

**Review by lehmann-4178656ch — APPROVED** [review]
I've tested the set of changes as well and they are looking good!

**Comment by hannahbast** [comment]
Thanks, but you were a bit too fast. I was still testing and there was still a small bug.

**Pull request merged**
